name: equipo_health
description: Develop a Health Care Application using flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  firebase_database: ^10.4.9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.4
  google_fonts: ^6.2.0
  intl: ^0.18.1
  ionicons: ^0.2.2
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
#  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png
