// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
///
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_TSqIIiMflc1geSR76jSpqbxLI9UsX0M',
    appId: '1:79753342196:web:379999a698c90627fb02a1',
    messagingSenderId: '79753342196',
    projectId: 'aut-improtion',
    authDomain: 'aut-improtion.firebaseapp.com',
    databaseURL: 'https://aut-improtion.firebaseio.com',
    storageBucket: 'aut-improtion.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5kOsRKaM9tPovy45H3ugZ5iBbqIf5xF0',
    appId: '1:79753342196:android:023ecf1e62c13e55fb02a1',
    messagingSenderId: '79753342196',
    projectId: 'aut-improtion',
    databaseURL: 'https://aut-improtion.firebaseio.com',
    storageBucket: 'aut-improtion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvy5dYAVdFsspjhPTXRJM-upyl4JqUBhU',
    appId: '1:79753342196:ios:5bff7ba2e7c23584fb02a1',
    messagingSenderId: '79753342196',
    projectId: 'aut-improtion',
    databaseURL: 'https://aut-improtion.firebaseio.com',
    storageBucket: 'aut-improtion.appspot.com',
    androidClientId: '79753342196-gacnv63iu0dsguh0v3rbu6b818pl82ht.apps.googleusercontent.com',
    iosBundleId: 'com.equipo.health.adhnan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvy5dYAVdFsspjhPTXRJM-upyl4JqUBhU',
    appId: '1:79753342196:ios:132152f4b6dc427afb02a1',
    messagingSenderId: '79753342196',
    projectId: 'aut-improtion',
    databaseURL: 'https://aut-improtion.firebaseio.com',
    storageBucket: 'aut-improtion.appspot.com',
    androidClientId: '79753342196-gacnv63iu0dsguh0v3rbu6b818pl82ht.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
